[package]
name = "raytracing"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]
exclude = []
resolver = "2"

[workspace.dependencies]
raytracing_core = { path = "./crates/raytracing_core" }
raytracing_config = { path = "./crates/raytracing_config" }
raytracing_cli = { path = "./crates/raytracing_cli" }
raytracing_renderer = { path = "./crates/raytracing_renderer" }
glam = { version = "0.29.0", features = ["serde"] }


[dependencies]
csgrs = "0.20.1"
raytracing_cli.workspace = true
raytracing_renderer.workspace = true
raytracing_core.workspace = true
raytracing_config.workspace = true
