[simulation_settings]
infinity_distance = 50.0
max_bounces = 10

[[rays]]
origin = [-15.0, 2.0, 0.0]
direction = [1.0, 0.0, 0.0]
current_ior = 1.0

[[objects]]
# Sphere
shape = { type = "Sphere", radius = 2.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [0.0, 0.0, 0.0] }

[[objects]]
# Box
shape = { type = "Box", size = [3.0, 3.0, 3.0] }
material = { type = "Mirror" }
transform = { position = [0.0, 0.0, -8.0] }

[[objects]]
# Wedge
shape = { type = "Wedge", size = [4.0, 3.0, 2.0], angle_deg = 30.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [0.0, 0.0, 8.0] }

[[objects]]
# Lens
shape = { type = "Lens", thickness = 1.0, diameter = 4.0, r1 = 5.0, r2 = -5.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [8.0, 0.0, 0.0] }
