[[rays]]
origin = [-10.0, 2.0, 0.0]
direction = [1.0, 0.0, 0.0]
current_ior = 1.0

[[objects]]
# 球 (Sphere)
shape = { type = "Sphere", radius = 5.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [0.0, 0.0, 0.0], rotation_y_deg = 0.0 }
