[simulation_settings]
infinity_distance = 50.0
max_bounces = 100
samples_per_pixel = 50
image_width = 800
image_height = 600

# === レイ生成ルール ===



# === 個別に配置するオブジェクト ===
[[scene.objects]]
# 床
shape = { type = "Plane", normal = [0.0, 1.0, 0.0] }
material = { type = "Diffuse", color = [0.8, 0.8, 0.8]}
transform = { position = [0.0, -10.0, 0.0], rotation_x_deg = 0.0 }


[camera]
lookfrom = [0.0, 0.0, 30.0]
lookat = [0.0, 0.0, 0.0]
vfov = 90.0


[[scene.objects]]
# 床
shape = { type = "Plane", normal = [0.0, 1.0, 0.0] }
material = { type = "Light", color = [1.0, 1.0, 1.0] }
transform = { position = [0.0, 30.0, 0.0], rotation_y_deg = 0.0 }



# [[scene.objects]]
# shape = { type = "Lens", thickness = 1.0, diameter = 9.0, r1 = 9.0, r2 = 9.0 }
# material = { type = "Glass", color = [1.0 , 0.01, 0.00], ior = 1.52 }
# transform = { position = [0.0, 0.0, 10.0], rotation_z_deg = 0.0,rotation_y_deg = 0.0 }

[[scene.objects]]
shape = { type = "Lens", thickness = 3.0, diameter = 5.0, r1 = 12.0, r2 = 12.0 }
material = { type = "Diffuse", color = [0.0, 0.0, 1.0]}
transform = { position = [0.0, 0.0, 10.0], rotation_y_deg = 90.0}

  
# 3. オブジェクトのグリッド配置
[[scene.object_generators]]
type = "ObjectGrid"
count_x = 5
count_z = 5
position_start = [3.0, 0.0, -10.0] # グリッドの開始位置
step_x = [5.0, 0.0, 0.0]             # X方向の配置ステップ
step_z = [0.0, 0.0, -5.0]            # Z方向の配置ステップ

# グリッド配置するオブジェクトのテンプレート
template.shape = { type = "Sphere", radius = 1.5 }
template.material = { type = "Diffuse", color = [0.8, 0.3, 0.3] }
template.transform = { position = [0.0, 0.0, 0.0], rotation_y_deg = 0.0 }

[[scene.objects]]
shape = { type = "Cylinder", height = 20.0, radius = 5.0}
material = { type = "Diffuse", color = [0.2, 0.6, 0.8] }
transform = { position = [0.0, 0.0, -10.0], rotation_x_deg = 0.0, rotation_y_deg = 0.0, rotation_z_deg = 0.0 }
