[settings]
infinity_distance = 50.0 # レイが何にも衝突しなかった場合に、この距離だけ進んで描画を終える
max_bounces = 10          # 最大の衝突回数

[[scene.rays]]
origin = [-10.0, 2.0, -2.0]
direction = [1.0, 0.0, 0.0]
current_ior = 1.0

[[scene.objects]]
# 球 (Sphere)
shape = { type = "Sphere", radius = 5.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [0.0, 0.0, 0.0], rotation_y_deg = 0.0 }

[[scene.objects]]
# 球 (Sphere)
shape = { type = "Sphere", radius = 5.0 }
material = { type = "Glass", ior = 1.5 }
transform = { position = [15.0, 2.5, 2.5], rotation_y_deg = 0.0 }