[simulation_settings]
infinity_distance = 50.0
max_bounces = 10

# === レイ生成ルール ===
# 2. プロジェクターのような点光源
[[scene.ray_generators]]
type = "Projector"
origin = [-15.0, 0.0, 0.0]         # 光源の単一の始点
target_corner = [-5.0, -5.0, -5.0] # 投影面の開始角
target_u = [0.0, 10.0, 0.0]        # 投影面のU方向ベクトル
target_v = [0.0, 0.0, 10.0]        # 投影面のV方向ベクトル
count_u = 3                      # U方向のレイの数
count_v = 1                       # V方向のレイの数
current_ior = 1.0
# === オブジェクト生成ルール ===

# 3. オブジェクトのグリッド配置
[[scene.object_generators]]
type = "ObjectGrid"
count_x = 5
count_z = 5
position_start = [-10.0, -10.0, 10.0] # グリッドの開始位置
step_x = [5.0, 0.0, 0.0]             # X方向の配置ステップ
step_z = [0.0, 0.0, -5.0]            # Z方向の配置ステップ

# グリッド配置するオブジェクトのテンプレート
template.shape = { type = "Sphere", radius = 1.5 }
template.material = { type = "Glass", ior = 1.5 }
template.transform = { position = [0.0, 0.0, 0.0], rotation_y_deg = 0.0 }
# === 個別に配置するオブジェクト ===
[[scene.objects]]
# 床
shape = { type = "Plane", normal = [0.0, 1.0, 0.0] }
material = { type = "Glass", ior = 1.2}
transform = { position = [0.0, -10.0, 0.0], rotation_y_deg = 0.0 }


[[scene.objects]]
shape = { type = "Plane", normal = [0.0, 1.0, 0.0] }
material = { type = "Glass", ior = 1.2 }
transform = { position = [0.0, -10.0, 0.0],rotation_y_deg = 0.0 }