[package]
name = "raytracing_core"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.8.3"
glam = "0.29.0"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"