use cust::prelude::*;
use glam::Vec3;
use image::{ImageBuffer, Rgb};
use raytracing_config::model::camera_config::CameraConfig;
use raytracing_core::{Hittable, HittableList, Material, Plane, Scene, Sphere, Transform};
use raytracing_cuda_kernel::{
    GpuAxisAlignedBox, GpuCamera, GpuHittable, GpuInfiniteCylinder, GpuMaterial,
};
use std::error::Error;

// This embeds the PTX file generated by the build script
const PTX: &str = include_str!(env!("KERNEL_PTX_PATH"));

/// Converts the CPU-side scene representation (using trait objects)
/// into a flat list of GPU-compatible structs.
struct GpuSceneConverter {
    gpu_hittables: Vec<GpuHittable>,
}

impl GpuSceneConverter {
    fn new() -> Self {
        Self {
            gpu_hittables: Vec::new(),
        }
    }

    fn convert(mut self, scene: &Scene) -> Vec<GpuHittable> {
        self.flatten_hittable(scene.world.as_ref(), glam::Mat4::IDENTITY);
        self.gpu_hittables
    }

    fn flatten_hittable(&mut self, hittable: &dyn Hittable, transform: glam::Mat4) {
        if let Some(s) = hittable.downcast_ref::<Sphere>() {
            let center = transform.transform_point3(s.center);
            self.gpu_hittables.push(GpuHittable::Sphere(
                raytracing_cuda_kernel::Sphere {
                    center,
                    radius: s.radius,
                    material: self.convert_material(s.material),
                },
            ));
        } else if let Some(p) = hittable.downcast_ref::<Plane>() {
            let point = transform.transform_point3(p.point);
            let normal = transform.transform_vector3(p.normal).normalize();
            self.gpu_hittables.push(GpuHittable::Plane(
                raytracing_cuda_kernel::Plane {
                    point,
                    normal,
                    material: self.convert_material(p.material),
                },
            ));
        } else if let Some(b) = hittable.downcast_ref::<raytracing_core::AxisAlignedBox>() {
             self.gpu_hittables.push(GpuHittable::AxisAlignedBox(
                GpuAxisAlignedBox {
                    min: transform.transform_point3(b.min),
                    max: transform.transform_point3(b.max),
                    material: self.convert_material(b.material),
                },
            ));
        } else if let Some(c) = hittable.downcast_ref::<raytracing_core::InfiniteCylinder>() {
             self.gpu_hittables.push(GpuHittable::InfiniteCylinder(
                GpuInfiniteCylinder {
                    axis_point: transform.transform_point3(c.axis_point),
                    axis_dir: transform.transform_vector3(c.axis_dir).normalize(),
                    radius: c.radius,
                    material: self.convert_material(c.material),
                },
            ));
        } else if let Some(list) = hittable.downcast_ref::<HittableList>() {
            for obj in &list.objects {
                self.flatten_hittable(obj.as_ref(), transform);
            }
        } else if let Some(t) = hittable.downcast_ref::<Transform>() {
            let composed_transform = transform * t.transform;
            self.flatten_hittable(t.primitive.as_ref(), composed_transform);
        }
        // Other hittable types like BVH, CSG, etc., are ignored for this CUDA implementation.
    }

    fn convert_material(&self, mat: Material) -> GpuMaterial {
        match mat {
            Material::Metal { color, fuzz } => GpuMaterial::Metal { color, fuzz },
            Material::Glass { color, ior } => GpuMaterial::Glass { color, ior },
            Material::HalfMirror { reflectance } => GpuMaterial::HalfMirror { reflectance },
            Material::Diffuse { color } => GpuMaterial::Diffuse { color },
            Material::Light { color } => GpuMaterial::Light { color },
        }
    }
}

/// Renders the scene using the CUDA kernel and saves it to a file.
pub fn render(
    scene: &Scene,
    camera_config: &CameraConfig,
    width: u32,
    height: u32,
    samples_per_pixel: u32,
    max_depth: u32,
) -> Result<(), Box<dyn Error>> {
    // --- 1. Initialize CUDA and Load Kernel ---
    let _ctx = cust::quick_init()?;
    let module = Module::from_str(PTX)?;
    let stream = Stream::new(StreamFlags::DEFAULT, None)?;

    // --- 2. Convert Scene to GPU format ---
    let converter = GpuSceneConverter::new();
    let gpu_hittables = converter.convert(scene);

    if gpu_hittables.is_empty() {
        println!("Warning: No compatible objects found for GPU rendering. Ensure your scene contains Spheres, Planes, Boxes, or Cylinders.");
        // Create a blank image
        let img_buf: ImageBuffer<Rgb<u8>, Vec<u8>> =
            ImageBuffer::from_pixel(width, height, Rgb([0, 0, 0]));
        img_buf.save("output.png").unwrap();
        println!("Saved a blank 'output.png'.");
        return Ok(());
    }

    // --- 3. Setup Camera ---
    let camera = GpuCamera::new(
        camera_config.lookfrom,
        camera_config.lookat,
        camera_config.vup,
        camera_config.vfov,
        width as f32 / height as f32,
    );

    // --- 4. Allocate and Copy Data to GPU ---
    let hittables_gpu = DeviceBuffer::from_slice(&gpu_hittables)?;
    let camera_gpu = DeviceBuffer::from_slice(&[camera])?;
    let mut output_gpu = unsafe { DeviceBuffer::uninitialized((width * height) as usize)? };

    // --- 5. Launch Kernel ---
    let grid_size = (width * height + 255) / 256;
    let block_size = 256;

    let kernel = module.get_function("render_kernel")?;

    unsafe {
        launch!(
            kernel<<<grid_size, block_size, 0, stream>>>(
                hittables_gpu.as_device_ptr(),
                gpu_hittables.len() as u32,
                camera_gpu.as_device_ptr(),
                output_gpu.as_device_ptr(),
                width,
                height,
                samples_per_pixel,
                max_depth as i32
            )
        )?;
    }
    stream.synchronize()?;

    // --- 6. Copy Result from GPU and Save Image ---
    let mut output_cpu = vec![Vec3::ZERO; (width * height) as usize];
    output_gpu.copy_to(&mut output_cpu)?;

    let pixels: Vec<Rgb<u8>> = output_cpu
        .into_iter()
        .map(|pixel_color| {
            // Apply gamma correction (sqrt)
            let r = (pixel_color.x).sqrt();
            let g = (pixel_color.y).sqrt();
            let b = (pixel_color.z).sqrt();
            Rgb([
                (256.0 * r.clamp(0.0, 0.999)) as u8,
                (256.0 * g.clamp(0.0, 0.999)) as u8,
                (256.0 * b.clamp(0.0, 0.999)) as u8,
            ])
        })
        .collect();

    let raw_pixels: Vec<u8> = pixels.into_iter().flat_map(|p| p.0).collect();
    let img_buf: ImageBuffer<Rgb<u8>, Vec<u8>> =
        ImageBuffer::from_raw(width, height, raw_pixels).unwrap();

    img_buf.save("output.png").unwrap();
    println!("GPUレンダリングが完了し、'output.png' に保存されました。");

    Ok(())
}