[package]
name = "raytracing_config"
version = "0.1.0"
edition = "2024"


[dependencies]
rand = "0.8.3"
glam = "0.29.0"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
raytracing_core.workspace = true
