[package]
name = "raytracing_renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
raytracing_core = { workspace = true }
raytracing_config = { workspace = true }
glam = { workspace = true }
image = "0.25.1"
rand = "0.8"
rayon = "1.5"

# CUDA dependencies
cust = "0.3.2"
raytracing_cuda_kernel = { path = "../raytracing_cuda_kernel" }

[build-dependencies]
cuda_builder = { git = "https://github.com/Rust-GPU/Rust-CUDA.git", package = "cuda_builder" }