use glam::Vec3;
use raytracing_config::simulation_config::SimulationConfig;
use raytracing_core::Scene;
use std::error::Error;
use std::fs::File;
use std::io::{Result as IoResult, Write};

/// Exports the calculated ray paths to a .obj file as a series of line segments.
fn export_paths_to_obj(results: &Vec<Vec<Vec3>>, filename: &str) -> IoResult<()> {
    let mut file = File::create(filename)?;

    writeln!(
        file,
        "# Light path visualization generated by raytracing-cli"
    )?;
    writeln!(file, "# Vertices")?;

    // Write all points from all paths as vertices
    for path in results {
        for point in path {
            writeln!(file, "v {} {} {}", point.x, point.y, point.z)?;
        }
    }

    writeln!(file, "\n# Line segments")?;
    let mut vertex_offset = 1; // OBJ indices are 1-based
    for path in results {
        if path.len() > 1 {
            // Create line segments between consecutive vertices in the current path
            for i in 0..path.len() - 1 {
                writeln!(file, "l {} {}", vertex_offset + i, vertex_offset + i + 1)?;
            }
        }
        // Increase the offset for the next path's indices
        vertex_offset += path.len();
    }

    println!("\n光路を {} にエクスポートしました。", filename);
    Ok(())
}

pub fn cli() -> Result<(), Box<dyn Error>> {
    println!("設定ファイル simulation.toml を読み込んでいます...");
    let SimulationConfig {
        scene,
        simulation_settings,
        ..
    } = SimulationConfig::load_from_path("simulation.toml")?;
    let scene: Scene = scene.into();
    let results = scene.simulate_rays(simulation_settings.into());

    println!("光路の計算が完了しました。");
    println!("計算された光路の数: {}", results.len());
    for (i, path) in results.iter().enumerate() {
        println!("--- 光路 {} ---", i);
        for (j, point) in path.iter().enumerate() {
            println!(
                "  点 {}: ({:.3}, {:.3}, {:.3})",
                j, point.x, point.y, point.z
            );
        }
    }

    // Export the results to an OBJ file
    if let Err(e) = export_paths_to_obj(&results, "paths.obj") {
        eprintln!("OBJファイルのエクスポートに失敗しました: {}", e);
    }

    Ok(())
}
