use clap::{Parser, Subcommand};
use glam::Vec3;
use raytracing_config::simulation_config::SimulationConfig;
use raytracing_core::Scene;
use raytracing_renderer::render;
use std::error::Error;
use std::fs::File;
use std::io::{Result as IoResult, Write};
use std::path::PathBuf;

#[derive(Parser)]
#[command(author, version, about, long_about = None)]
#[command(propagate_version = true)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Trace rays based on a simulation configuration and output an OBJ file
    Trace {
        /// Path to the simulation configuration file
        #[arg(short, long, value_name = "FILE", default_value = "simulation.toml")]
        config: PathBuf,

        /// Path to the output OBJ file
        #[arg(short, long, value_name = "FILE", default_value = "paths.obj")]
        output: PathBuf,
    },
    /// Render a scene to an image file
    Render {
        /// Path to the simulation configuration file
        #[arg(short, long, value_name = "FILE", default_value = "simulation.toml")]
        config: PathBuf,

        /// Path to the output image file
        #[arg(short, long, value_name = "FILE", default_value = "output.png")]
        output: PathBuf,

        /// Override image width
        #[arg(long)]
        width: Option<u32>,

        /// Override image height
        #[arg(long)]
        height: Option<u32>,

        /// Override samples per pixel
        #[arg(long)]
        samples: Option<u32>,

        /// Override max bounces
        #[arg(long)]
        bounces: Option<u32>,
    },
}

/// Exports the calculated ray paths to a .obj file as a series of line segments.
fn export_paths_to_obj(results: &Vec<Vec<Vec3>>, filename: &PathBuf) -> IoResult<()> {
    let mut file = File::create(filename)?;
    writeln!(
        file,
        "# Light path visualization generated by raytracing-cli"
    )?;
    writeln!(file, "# Vertices")?;
    for path in results {
        for point in path {
            writeln!(file, "v {} {} {}", point.x, point.y, point.z)?;
        }
    }
    writeln!(file, "
# Line segments")?;
    let mut vertex_offset = 1;
    for path in results {
        if path.len() > 1 {
            for i in 0..path.len() - 1 {
                writeln!(file, "l {} {}", vertex_offset + i, vertex_offset + i + 1)?;
            }
        }
        vertex_offset += path.len();
    }
    println!("
光路を {:?} にエクスポートしました。", filename);
    Ok(())
}

pub fn cli() -> Result<(), Box<dyn Error>> {
    let cli = Cli::parse();

    match &cli.command {
        Commands::Trace { config, output } => {
            println!("設定ファイル {:?} を読み込んでいます...", config);
            let sim_config = SimulationConfig::load_from_path(config)?;
            let scene: Scene = sim_config.scene.into();

            println!("光路の計算を開始します...");
            let results = scene.simulate_rays(sim_config.simulation_settings.into());
            println!("光路の計算が完了しました。 {}個の光路が見つかりました。", results.len());

            if let Err(e) = export_paths_to_obj(&results, output) {
                eprintln!("OBJファイルのエクスポートに失敗しました: {}", e);
            }
        }
        Commands::Render {
            config,
            output,
            width,
            height,
            samples,
            bounces,
        } => {
            println!("設定ファイル {:?} を読み込んでいます...", config);
            let sim_config = SimulationConfig::load_from_path(config)?;
            let scene: Scene = sim_config.scene.into();
            let camera_config = sim_config.camera;
            let mut settings = sim_config.simulation_settings;

            // Override settings if provided
            if let Some(w) = width { settings.image_width = *w; }
            if let Some(h) = height { settings.image_height = *h; }
            if let Some(s) = samples { settings.samples_per_pixel = *s; }
            if let Some(b) = bounces { settings.max_bounces = *b; }


            println!("レンダリングを開始します...");
            render(
                &scene,
                &camera_config,
                settings.image_width,
                settings.image_height,
                settings.samples_per_pixel,
                settings.max_bounces,
                output,
            );
            println!("レンダリングが完了しました。出力先: {:?}", output);
        }
    }

    Ok(())
}