pub mod material_config;
pub mod object_config;
pub mod object_generator_config;
pub mod ray_config;
pub mod scene_config;
pub mod shape_config;
pub mod simulation_config;
pub mod simulation_settings_config;
pub mod transform_config;
